package com.example.shopapp.model.findingApi

data class FindResponse(
    val findItemsByKeywordsResponse: List<FindItemsByKeywordsResponse>
)
//Example response

//{"findItemsByKeywordsResponse":[
//    {
//        "ack":["Success"], "version":["1.13.0"], "timestamp":["2022-04-09T18:21:25.862Z"], "searchResult":[{
//        "@count":"10", "item":[{
//        "itemId":["254505347259"], "title":["Harry Potter and the Order of the Phoenix (Book 5) - Hardcover - GOOD"], "globalId":["EBAY-US"], "primaryCategory":[{ "categoryId":["261186"], "categoryName":["Books"] }], "galleryURL":["https:\/\/i.ebayimg.com\/thumbs\/images\/g\/jIQAAOSwtnJgnRpO\/s-l140.jpg"], "viewItemURL":["https:\/\/www.ebay.com\/itm\/Harry-Potter-and-Order-Phoenix-Book-5-Hardcover-GOOD-\/254505347259"], "productId":[{ "@type":"ReferenceID", "__value__":"16038295329" }], "autoPay":["true"], "postalCode":["605**"], "location":["Montgomery,IL,USA"], "country":["US"], "shippingInfo":[{ "shippingServiceCost":[{ "@currencyId":"USD", "__value__":"0.0" }], "shippingType":["Free"], "shipToLocations":["Worldwide"], "expeditedShipping":["true"], "oneDayShippingAvailable":["false"], "handlingTime":["1"] }], "sellingStatus":[{ "currentPrice":[{ "@currencyId":"USD", "__value__":"4.3" }], "convertedCurrentPrice":[{ "@currencyId":"USD", "__value__":"4.3" }], "sellingState":["Active"], "timeLeft":["P27DT2H9M58S"] }], "listingInfo":[{ "bestOfferEnabled":["false"], "buyItNowAvailable":["false"], "startTime":["2020-02-06T20:31:23.000Z"], "endTime":["2022-05-06T20:31:23.000Z"], "listingType":["FixedPrice"], "gift":["false"], "watchCount":["120"] }], "returnsAccepted":["true"], "condition":[{ "conditionId":["5000"], "conditionDisplayName":["Good"] }], "isMultiVariationListing":["false"], "topRatedListing":["false"]
//    },{
//        "itemId":["302485416770"],
//        "title":["Harry Potter and the Order of the Phoenix (Book 5)"],
//        "globalId":["EBAY-US"], "subtitle":["by J. K. Rowling | Hardcover"],
//        "primaryCategory":[{ "categoryId":["261186"], "categoryName":["Books"] }],
//        "galleryURL":["https:\/\/i.ebayimg.com\/thumbs\/images\/g\/a4MAAOSwJ5NZ30W1\/s-l140.jpg"],
//        "viewItemURL":["https:\/\/www.ebay.com\/itm\/Harry-Potter-and-Order-Phoenix-Book-5-\/302485416770"],
//        "productId":[{ "@type":"ReferenceID", "__value__":"16038295329" }],
//        "autoPay":["false"], "postalCode":["436**"], "location":["Toledo,OH,USA"],
//        "country":["US"],
//        "shippingInfo":[{
//            "shippingServiceCost":[{ "@currencyId":"USD", "__value__":"0.0" }],
//            "shippingType":["Free"], "shipToLocations":["Worldwide"], "expeditedShipping":["false"],
//            "oneDayShippingAvailable":["false"], "handlingTime":["2"]
//        }],
//        "sellingStatus":[{
//            "currentPrice":[{ "@currencyId":"USD", "__value__":"4.49" }],
//            "convertedCurrentPrice":[{ "@currencyId":"USD", "__value__":"4.49" }],
//            "sellingState":["Active"], "timeLeft":["P2DT16H15M7S"]
//        }],
//        "listingInfo":[{
//            "bestOfferEnabled":["false"],
//            "buyItNowAvailable":["false"],
//            "startTime":["2017-10-12T10:36:32.000Z"],
//            "endTime":["2022-04-12T10:36:32.000Z"],
//            "listingType":["FixedPrice"],
//            "gift":["false"], "watchCount":["153"]
//        }],
//        "returnsAccepted":["true"],
//        "condition":[{
//            "conditionId":["5000"],
//            "conditionDisplayName":["Good"]
//        }],
//        "isMultiVariationListing":["false"],
//        "topRatedListing":["false"]
//    },{
//        "itemId":["193485691113"], "title":["Harry Potter and the Order of the Phoenix by J. K. Rowling"], "globalId":["EBAY-US"], "subtitle":["by J. K. Rowling | HC | Acceptable"], "primaryCategory":[{ "categoryId":["261186"], "categoryName":["Books"] }], "galleryURL":["https:\/\/i.ebayimg.com\/thumbs\/images\/g\/4aQAAOSwbM5gADQy\/s-l140.jpg"], "viewItemURL":["https:\/\/www.ebay.com\/itm\/Harry-Potter-and-Order-Phoenix-J-K-Rowling-\/193485691113"], "productId":[{ "@type":"ReferenceID", "__value__":"16038295329" }], "autoPay":["true"], "postalCode":["605**"], "location":["Aurora,IL,USA"], "country":["US"], "shippingInfo":[{ "shippingServiceCost":[{ "@currencyId":"USD", "__value__":"0.0" }], "shippingType":["Free"], "shipToLocations":["Worldwide"], "expeditedShipping":["true"], "oneDayShippingAvailable":["false"], "handlingTime":["1"] }], "sellingStatus":[{ "currentPrice":[{ "@currencyId":"USD", "__value__":"4.74" }], "convertedCurrentPrice":[{ "@currencyId":"USD", "__value__":"4.74" }], "sellingState":["Active"], "timeLeft":["P18DT18H3M13S"] }], "listingInfo":[{ "bestOfferEnabled":["false"], "buyItNowAvailable":["false"], "startTime":["2020-05-28T12:24:38.000Z"], "endTime":["2022-04-28T12:24:38.000Z"], "listingType":["FixedPrice"], "gift":["false"], "watchCount":["162"] }], "returnsAccepted":["true"], "condition":[{ "conditionId":["6000"], "conditionDisplayName":["Acceptable"] }], "isMultiVariationListing":["false"], "topRatedListing":["true"]
//    },{
//        "itemId":["274283728654"], "title":["Harry Potter And The Order Of The Phoenix - Paperback By Rowling, J.K. - GOOD"], "globalId":["EBAY-US"], "primaryCategory":[{ "categoryId":["261186"], "categoryName":["Books"] }], "galleryURL":["https:\/\/i.ebayimg.com\/thumbs\/images\/g\/W-4AAOSw~E9gpH7t\/s-l140.jpg"], "viewItemURL":["https:\/\/www.ebay.com\/itm\/Harry-Potter-And-Order-Phoenix-Paperback-Rowling-J-K-GOOD-\/274283728654"], "productId":[{ "@type":"ReferenceID", "__value__":"30259808" }], "autoPay":["true"], "postalCode":["605**"], "location":["Montgomery,IL,USA"], "country":["US"], "shippingInfo":[{ "shippingServiceCost":[{ "@currencyId":"USD", "__value__":"0.0" }], "shippingType":["Free"], "shipToLocations":["Worldwide"], "expeditedShipping":["true"], "oneDayShippingAvailable":["false"], "handlingTime":["1"] }], "sellingStatus":[{ "currentPrice":[{ "@currencyId":"USD", "__value__":"4.2" }], "convertedCurrentPrice":[{ "@currencyId":"USD", "__value__":"4.2" }], "sellingState":["Active"], "timeLeft":["P13DT12H28M15S"] }], "listingInfo":[{ "bestOfferEnabled":["false"], "buyItNowAvailable":["false"], "startTime":["2020-02-23T06:49:40.000Z"], "endTime":["2022-04-23T06:49:40.000Z"], "listingType":["FixedPrice"], "gift":["false"], "watchCount":["134"] }], "returnsAccepted":["true"], "condition":[{ "conditionId":["5000"], "conditionDisplayName":["Good"] }], "isMultiVariationListing":["false"], "topRatedListing":["false"]
//    },{
//        "itemId":["373735639910"], "title":["Harry Potter and the Order of the Phoenix (5) by Rowling, J. K."], "globalId":["EBAY-US"], "subtitle":["by Rowling, J. K. | PB | Good"], "primaryCategory":[{ "categoryId":["261186"], "categoryName":["Books"] }], "galleryURL":["https:\/\/i.ebayimg.com\/thumbs\/images\/g\/fPQAAOSw1Gxf~bEv\/s-l140.jpg"], "viewItemURL":["https:\/\/www.ebay.com\/itm\/Harry-Potter-and-Order-Phoenix-5-Rowling-J-K-\/373735639910"], "productId":[{ "@type":"ReferenceID", "__value__":"30259808" }], "autoPay":["true"], "postalCode":["605**"], "location":["Aurora,IL,USA"], "country":["US"], "shippingInfo":[{ "shippingServiceCost":[{ "@currencyId":"USD", "__value__":"0.0" }], "shippingType":["Free"], "shipToLocations":["Worldwide"], "expeditedShipping":["true"], "oneDayShippingAvailable":["false"], "handlingTime":["1"] }], "sellingStatus":[{ "currentPrice":[{ "@currencyId":"USD", "__value__":"4.09" }], "convertedCurrentPrice":[{ "@currencyId":"USD", "__value__":"4.09" }], "sellingState":["Active"], "timeLeft":["P17DT4H52M11S"] }], "listingInfo":[{ "bestOfferEnabled":["false"], "buyItNowAvailable":["false"], "startTime":["2021-09-26T23:13:36.000Z"], "endTime":["2022-04-26T23:13:36.000Z"], "listingType":["FixedPrice"], "gift":["false"], "watchCount":["17"] }], "returnsAccepted":["true"], "condition":[{ "conditionId":["5000"], "conditionDisplayName":["Good"] }], "isMultiVariationListing":["false"], "topRatedListing":["true"]
//    },{
//        "itemId":["294912993120"], "title":["Harry Potter Ser.: Harry Potter and the Order of the Phoenix by J. K. Rowling."], "globalId":["EBAY-US"], "primaryCategory":[{ "categoryId":["261186"], "categoryName":["Books"] }], "galleryURL":["https:\/\/i.ebayimg.com\/thumbs\/images\/g\/0xgAAOSwbm9iR2Jg\/s-l140.jpg"], "viewItemURL":["https:\/\/www.ebay.com\/itm\/Harry-Potter-Ser-Harry-Potter-and-Order-Phoenix-J-K-Rowling-\/294912993120"], "productId":[{ "@type":"ReferenceID", "__value__":"16038295329" }], "autoPay":["false"], "postalCode":["215**"], "location":["Cumberland,MD,USA"], "country":["US"], "shippingInfo":[{ "shippingServiceCost":[{ "@currencyId":"USD", "__value__":"6.0" }], "shippingType":["Flat"], "shipToLocations":["Worldwide"], "expeditedShipping":["false"], "oneDayShippingAvailable":["false"], "handlingTime":["3"] }], "sellingStatus":[{ "currentPrice":[{ "@currencyId":"USD", "__value__":"9.99" }], "convertedCurrentPrice":[{ "@currencyId":"USD", "__value__":"9.99" }], "bidCount":["1"], "sellingState":["Active"], "timeLeft":["P6DT2H20M30S"] }], "listingInfo":[{ "bestOfferEnabled":["false"], "buyItNowAvailable":["false"], "startTime":["2022-04-08T20:41:55.000Z"], "endTime":["2022-04-15T20:41:55.000Z"], "listingType":["Auction"], "gift":["false"] }], "returnsAccepted":["false"], "condition":[{ "conditionId":["4000"], "conditionDisplayName":["Very Good"] }], "isMultiVariationListing":["false"], "topRatedListing":["false"]
//    },{
//        "itemId":["264887305289"], "title":["Harry Potter and the Order of the Phoenix - Hardcover By J.K. Rowling - GOOD"], "globalId":["EBAY-US"], "primaryCategory":[{ "categoryId":["261186"], "categoryName":["Books"] }], "galleryURL":["https:\/\/i.ebayimg.com\/thumbs\/images\/g\/eRUAAOSwTdRgq7Fs\/s-l140.jpg"], "viewItemURL":["https:\/\/www.ebay.com\/itm\/Harry-Potter-and-Order-Phoenix-Hardcover-J-K-Rowling-GOOD-\/264887305289"], "autoPay":["true"], "postalCode":["605**"], "location":["Montgomery,IL,USA"], "country":["US"], "shippingInfo":[{ "shippingServiceCost":[{ "@currencyId":"USD", "__value__":"0.0" }], "shippingType":["Free"], "shipToLocations":["Worldwide"], "expeditedShipping":["true"], "oneDayShippingAvailable":["false"], "handlingTime":["1"] }], "sellingStatus":[{ "currentPrice":[{ "@currencyId":"USD", "__value__":"4.39" }], "convertedCurrentPrice":[{ "@currencyId":"USD", "__value__":"4.39" }], "sellingState":["Active"], "timeLeft":["P24DT23H30M9S"] }], "listingInfo":[{ "bestOfferEnabled":["false"], "buyItNowAvailable":["false"], "startTime":["2020-10-04T17:51:34.000Z"], "endTime":["2022-05-04T17:51:34.000Z"], "listingType":["FixedPrice"], "gift":["false"], "watchCount":["5"] }], "returnsAccepted":["true"], "condition":[{ "conditionId":["5000"], "conditionDisplayName":["Good"] }], "isMultiVariationListing":["false"], "topRatedListing":["false"]
//    },{
//        "itemId":["193302088221"], "title":["Harry Potter and the Order of the Phoenix"], "globalId":["EBAY-US"], "subtitle":["by J. K. Rowling | Paperback"], "primaryCategory":[{ "categoryId":["261186"], "categoryName":["Books"] }], "galleryURL":["https:\/\/i.ebayimg.com\/thumbs\/images\/g\/mHoAAOSwctxeH5ll\/s-l140.jpg"], "viewItemURL":["https:\/\/www.ebay.com\/itm\/Harry-Potter-and-Order-Phoenix-\/193302088221"], "autoPay":["false"], "postalCode":["436**"], "location":["Toledo,OH,USA"], "country":["US"], "shippingInfo":[{ "shippingServiceCost":[{ "@currencyId":"USD", "__value__":"0.0" }], "shippingType":["Free"], "shipToLocations":["Worldwide"], "expeditedShipping":["false"], "oneDayShippingAvailable":["false"], "handlingTime":["2"] }], "sellingStatus":[{ "currentPrice":[{ "@currencyId":"USD", "__value__":"5.26" }], "convertedCurrentPrice":[{ "@currencyId":"USD", "__value__":"5.26" }], "sellingState":["Active"], "timeLeft":["P6DT4H38M21S"] }], "listingInfo":[{ "bestOfferEnabled":["false"], "buyItNowAvailable":["false"], "startTime":["2020-01-15T22:59:46.000Z"], "endTime":["2022-04-15T22:59:46.000Z"], "listingType":["FixedPrice"], "gift":["false"], "watchCount":["7"] }], "returnsAccepted":["true"], "condition":[{ "conditionId":["5000"], "conditionDisplayName":["Good"] }], "isMultiVariationListing":["false"], "topRatedListing":["false"]
//    },{
//        "itemId":["175226582176"], "title":["Harry Potter Ser.: Harry Potter and the Order of the Phoenix by J. K. Rowling..."], "globalId":["EBAY-US"], "primaryCategory":[{ "categoryId":["261186"], "categoryName":["Books"] }], "galleryURL":["https:\/\/i.ebayimg.com\/thumbs\/images\/g\/bdEAAOSwz~NiQKjA\/s-l140.jpg"], "viewItemURL":["https:\/\/www.ebay.com\/itm\/Harry-Potter-Ser-Harry-Potter-and-Order-Phoenix-J-K-Rowling-\/175226582176"], "productId":[{ "@type":"ReferenceID", "__value__":"242544279" }], "autoPay":["false"], "postalCode":["104**"], "location":["Bronx,NY,USA"], "country":["US"], "shippingInfo":[{ "shippingType":["Calculated"], "shipToLocations":["Worldwide"], "expeditedShipping":["false"], "oneDayShippingAvailable":["false"], "handlingTime":["2"] }], "sellingStatus":[{ "currentPrice":[{ "@currencyId":"USD", "__value__":"0.99" }], "convertedCurrentPrice":[{ "@currencyId":"USD", "__value__":"0.99" }], "bidCount":["0"], "sellingState":["Active"], "timeLeft":["P0DT23H57M41S"] }], "listingInfo":[{ "bestOfferEnabled":["false"], "buyItNowAvailable":["false"], "startTime":["2022-04-03T18:19:06.000Z"], "endTime":["2022-04-10T18:19:06.000Z"], "listingType":["Auction"], "gift":["false"], "watchCount":["1"] }], "returnsAccepted":["false"], "condition":[{ "conditionId":["5000"], "conditionDisplayName":["Good"] }], "isMultiVariationListing":["false"], "topRatedListing":["false"]
//    },{
//        "itemId":["144494588325"], "title":["Harry Potter Ser.: Harry Potter and the Order of the Phoenix by J. K. Rowling..."], "globalId":["EBAY-US"], "primaryCategory":[{ "categoryId":["261186"], "categoryName":["Books"] }], "galleryURL":["https:\/\/i.ebayimg.com\/thumbs\/images\/g\/0bcAAOSwVvtiUJXg\/s-l140.jpg"], "viewItemURL":["https:\/\/www.ebay.com\/itm\/Harry-Potter-Ser-Harry-Potter-and-Order-Phoenix-J-K-Rowling-\/144494588325"], "autoPay":["false"], "postalCode":["655**"], "location":["Lebanon,MO,USA"], "country":["US"], "shippingInfo":[{ "shippingServiceCost":[{ "@currencyId":"USD", "__value__":"0.0" }], "shippingType":["Free"], "shipToLocations":["Worldwide"], "expeditedShipping":["false"], "oneDayShippingAvailable":["false"], "handlingTime":["0"] }], "sellingStatus":[{ "currentPrice":[{ "@currencyId":"USD", "__value__":"14.0" }], "convertedCurrentPrice":[{ "@currencyId":"USD", "__value__":"14.0" }], "sellingState":["Active"], "timeLeft":["P29DT1H46M36S"] }], "listingInfo":[{ "bestOfferEnabled":["true"], "buyItNowAvailable":["false"], "startTime":["2022-04-08T20:08:01.000Z"], "endTime":["2022-05-08T20:08:01.000Z"], "listingType":["FixedPrice"], "gift":["false"] }], "returnsAccepted":["true"], "condition":[{ "conditionId":["4000"], "conditionDisplayName":["Very Good"] }], "isMultiVariationListing":["false"], "topRatedListing":["true"]
//    }]
//    }], "paginationOutput":[{ "pageNumber":["1"], "entriesPerPage":["10"], "totalPages":["1406"], "totalEntries":["14057"] }], "itemSearchURL":["https:\/\/www.ebay.com\/sch\/i.html?_nkw=harry+potter+phoenix&_ddo=1&_ipg=10&_pgn=1"]
//    }]
//}